"""Add as_at_date and version_string to chunk

Revision ID: 003
Revises: 002
Create Date: 2026-09-10

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('as_at_date', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('chunk', sa.Column('version_string', sa.String(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'version_string')
    op.drop_column('chunk', 'as_at_date')
    # ### end Alembic commands ###